import Head from "next/head";

//Components
import Layout from "../../app/core/layout";
import { Banner, TopSellers, LiveBidding } from "../../app/components/Home";

const Index = () => {
  return (
    <>
      <Head>
        <title>NFT - Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner />
        <div className="my-20 mx-28">
          <TopSellers />
          <LiveBidding />
        </div>
      </Layout>
    </>
  );
};

export default Index;
