import Head from "next/head";

//Components
import Layout from "../../app/core/layout";
import {
  Banner,
  TopSellers,
  LiveBidding,
  AllNFTs,
} from "../../app/components/Home";

const Index = () => {
  return (
    <>
      <Head>
        <title>NFT - Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Banner />
        <div className="my-20 lg:mx-28 md:px-10 px-5">
          <TopSellers />
          <LiveBidding />
          <AllNFTs />
        </div>
      </Layout>
    </>
  );
};

export default Index;
