import { useState } from "react";
import Head from "next/head";
import Layout from "../../app/core/layout";
import { Breadcrumb } from "../../app/components";
import { Checkbox, Input, Textarea } from "../../app/components/Utils";
import { FiChevronRight } from "react-icons/fi";
import { HiOutlineUpload } from "react-icons/hi";
import { portfolio05 } from "../../assets";

import Link from "next/link";
import Image from "next/image";
import { useRef } from "react";

const Index = () => {
  const [NFTImage, setNFTImage] = useState<string>("");

  const fileRef = useRef<HTMLInputElement | null>(null);

  const handleClickBoxFile = () => {
    fileRef.current?.click();
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.checked) {
      console.log("✅ Checkbox is checked");
    } else {
      console.log("⛔️ Checkbox is NOT checked");
    }
  };

  const handleChangeImage = async (e: any) => {
    const selectedFile = e.target.files[0];
    const reader = new FileReader();

    reader.onload = () => {
      if (reader.readyState === 2) {
        setNFTImage(reader.result);
      }
    };
    reader.readAsDataURL(selectedFile);
  };

  return (
    <>
      <Head>
        <title>NFT - Marketplace | Create Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Breadcrumb>
          <h1 className="text-2xl text-white font-semibold">
            Crete a New File
          </h1>
          <div className="flex items-center gap-2">
            <Link href="#">
              <a className="text-light hover:text-white duration-150 ease-linear">
                Home
              </a>
            </Link>
            <FiChevronRight className="text-light" />
            <Link href="#">
              <a className="text-white">Crete a New File</a>
            </Link>
          </div>
        </Breadcrumb>

        <div className="py-20 lg:px-48 px-5 w-full flex md:flex-row flex-col justify-between lg:gap-16 gap-6">
          <div className="md:w-1/3 w-full">
            <h2 className="text-white text-lg mb-2">Upload file</h2>
            <p className="text-light">Drag or choose your file to upload</p>
            <div
              className="mt-6 group relative flex justify-center items-center cursor-pointer border-2 border-dashed rounded-lg border-white/20"
              onClick={handleClickBoxFile}
            >
              <input
                type="file"
                ref={fileRef}
                name="NFT_image"
                className="hidden"
                onChange={handleChangeImage}
              />
              <Image
                src={NFTImage ? NFTImage : portfolio05}
                alt="bg-image"
                className="rounded-lg w-80"
                width={380}
                height={400}
              />

              <div className="absolute group-hover:scale-90 duration-200 ease-linear w-full top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center text-light">
                <HiOutlineUpload className="text-primary mx-auto" size={40} />
                <h6 className="font-medium text-xl my-4">Choose a File</h6>
                <p className="text-sm">PNG, GIF, WEBP, MP4 or MP3</p>
                <p className="text-sm mt-2">Max 1Gb</p>
              </div>
            </div>

            <div className="mt-24">
              <strong className="text-white text-xl">Note:</strong>
              <p className="text-light text-sm mt-3">
                Service fee : <span className="font-bold">2.5%</span>
              </p>
              <p className="text-light text-sm mt-1">
                You will receive :{" "}
                <span className="font-bold">25.00 ETH $50,000</span>
              </p>
            </div>
          </div>
          <div className="card-transparent flex flex-col gap-6 md:p-8 md:w-2/3 w-full">
            <div>
              <p className="text-light mb-2">Product Name</p>
              <Input
                type="text"
                placeholder="e.g. `Digital Awesome Game`"
                name="product_name"
              />
            </div>
            <div>
              <p className="text-light mb-2">Discription</p>
              <Textarea
                placeholder="e. g. “After purchasing the product you can get item...”"
                name="description"
              />
            </div>

            <div className="flex md:flex-row flex-col gap-3">
              <div>
                <p className="text-light mb-2">Item Price in $</p>
                <Input type="text" placeholder="e.g. `20$`" name="price" />
              </div>
              <div>
                <p className="text-light mb-2">Size</p>
                <Input type="text" placeholder="e.g. `Size`" name="size" />
              </div>
              <div>
                <p className="text-light mb-2">Propertie</p>
                <Input
                  type="text"
                  placeholder="e.g. `Propertie`"
                  name="propertie"
                />
              </div>
            </div>

            <div>
              <p className="text-light mb-2">Royality</p>
              <Input type="text" placeholder="e.g. `20%`" name="royality" />
            </div>

            <div className="flex md:flex-row flex-col gap-3">
              <Checkbox
                type="checkbox"
                name="put_on_sale"
                id="put_on_sale"
                text="Put on Sale"
                handleChange={handleChange}
              />
              <Checkbox
                type="checkbox"
                name="sale_price"
                id="sale_price"
                text="Instant Sale Price"
                handleChange={handleChange}
              />
              <Checkbox
                type="checkbox"
                name="unlock_purchased"
                id="unlock_purchased"
                text="Unlock Purchased"
                handleChange={handleChange}
              />
            </div>

            <div className="flex md:flex-row flex-col gap-4 w-full">
              <button className="btn btn-dark md:w-2/5 w-full">Preview</button>
              <button className="btn btn-primary md:w-3/5 w-full">
                Submit Item
              </button>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Index;
