import {
  client1,
  client2,
  client4,
  client5,
  client6,
  client8,
  client9,
  nft1,
  nft2,
  nft3,
  nft4,
  nft5,
  nft6,
  nft7,
} from "../assets";

export const products = [
  {
    id: "0001",
    Owner: { name: "Brodband", image: client1 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    cover: nft4,
    images: [nft1, nft2, nft3],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
  {
    id: "0002",
    Owner: { name: "Brodband", image: client2 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    cover: nft5,
    images: [nft1, nft2, nft3],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
  {
    id: "0003",
    Owner: { name: "Brodband", image: client2 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    cover: nft6,
    images: [nft1, nft2, nft3],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
  {
    id: "0004",
    Owner: { name: "Brodband", image: client2 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    cover: nft7,
    images: [nft1, nft2, nft3],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
  {
    id: "0005",
    Owner: { name: "Brodband", image: client2 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    cover: nft2,
    images: [nft1, nft2, nft3],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
];
