import {
  client1,
  client2,
  client4,
  client5,
  client6,
  client8,
  client9,
} from "../assets";

export const product = [
  {
    Owner: { name: "Brodband", image: client1 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    title: "The Amazing Game",
    images:[],
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
  {
    Owner: { name: "Brodband", image: client2 },
    title: "The Amazing Game",
    price: 0.11,
    "propertie-name": "#22 Portal",
    type: "10% royalties",
    title: "The Amazing Game",
    property: [
      { type: " HYPE TYPE", value: "CALM AF (STILL)" },
      { type: "BASTARDNESS", value: "C00LIO BASTARD" },
      { type: "TYPE", value: "APE" },
      { type: "ASTARDNESS", value: "BASTARD" },
      { type: "BAD HABIT(S)", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
    category: [
      { type: "ZARY", value: "APP" },
      { type: "SOMALIAN", value: "TRIBUTE" },
      { type: "TUNA", value: "PIPE" },
      { type: "BID", value: "BPEYti" },
      { type: "ASTRAGENAKAR", value: "BASTARD" },
      { type: "CITY", value: "TOKYO" },
    ],
  },
];
