import Head from "next/head";

//Components
import Layout from "../../app/core/layout";
import { Breadcrumb } from "../../app/components";

const ProductDetails = () => {
  return (
    <>
      <Head>
        <title>NFT - Marketplace | Product Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Breadcrumb />
        <div className="my-20 lg:mx-20 md:px-10 px-5">Product Details</div>
      </Layout>
    </>
  );
};

export default ProductDetails;
